### ISSUE TITLE
erro db conect

### ISSUE THREAD

**Issue by tgvieirabr** [Chinmay-Ankolekar/Hostel-Grievance-Redressal#1]
i need help to conect db

**Comment by Chinmay-Ankolekar** [comment]
Please check that the database credentials (user, password, host, port, database) are correct and that the PostgreSQL server is running on port 5432. Make sure there are no firewall or network restrictions blocking the connection. Let me know if any specific error messages appear, and I’d be happy to assist further!

First create database, and add block id and block name before adding user.
